[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "rust-lld"
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a72 -nographic -kernel"
rustflags = []

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
